### PR TITLE
fix(utils): Update Mapping import

### LINKED ISSUE #22: AttributeError: module 'collections' has no attribute 'Mapping'
Currently this library is not Python 3.10 compatible. This is due to the existing import on utils.py:

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

I'll submit a PR soon fixing this.

### PR DESCRIPTION
**Pull request by denisroldan**
Remove deprecation and make it work with Python 3.10.

Closes #22

### CODE REVIEW

**Review by hiimdoublej — APPROVED** [review]

**Comment by hiimdoublej** [comment]
Thanks for the contribution !
